In [21]:
import pandas as pd #Pandas is a library where we can handle data-related tasks, and 'as pd' means alias name for pandas

In [2]:
dataset=pd.read_csv("Salary_Data.csv") #read the input file and store/assign in to one variable

In [3]:
dataset #the variable is having input dataset (full structure) and simply we can run the assigned variable, it will show whatever is being held

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [5]:
independent=dataset[["YearsExperience"]] #independent variable means it holds input values from dataset

In [7]:
independent #(display the input value) simply we can run the assigned variable, it will show whatever is being held

   YearsofExperience
0                1.1
1                1.0
2                3.0
3                2.0
4                2.8
5                4.0
6                4.8
7                5.0
8                6.4
9                7.0

In [6]:
dependent=dataset[["Salary"]] #dependent variable means it holds output values from dataset

In [9]:
dependent #(display the output value) simply we can run the assigned variable, it will show whatever is being held

   Salary
0   23000
1   20000
2   33000
3   31000
4   28000
5   41000
6   49000
7   55000
8   65000
9   77000

In [11]:
#Splitting the train and test data by using the train test split function from sklearn.
#And here assigning the independent and dependent data set respectively to the train and test variable. 
#also used test_size and randam stage for splitting the datas according to the given limits.
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30,random_state=0)

In [13]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)
'''the linearregression function is used for fit the input and output values which means used to create the model'''

'the linearregression function is used for fit the input and output values which means used to create the model'

In [14]:
weight=regressor.coef_
weight
'''coef is used to get the weight value from train model'''

'coef is used to get the weight value from train model'

In [17]:
bais=regressor.intercept_
bais
'''intercept is used to get the bais value from train model'''

array([11258.0329701])

In [24]:
y_pred=regressor.predict(X_test)
#predict function is used for predict the value from input test dataset for validation purpose (becz already we have output test dataset for comparison)

In [25]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
#as mentioned earlier, we can validate between trained model(predicted) with test output

In [23]:
r_score ##'''r_score is helped to get the difference value between test and predicted value, if we get lesser than 1 score values , then we can 
##consider this is a good model else it is a bad model(need to recheck) '''

0.9740993407213511

In [26]:
import pickle #pickle function is used to store the model and output check from trained model
filename1="finalized_model_linear.sav"

In [27]:
pickle.dump(regressor,open(filename1,'wb')) # dump means store the trained model with write binary mode

In [28]:
loaded_model=pickle.load(open("finalized_model_linear.sav",'rb')) # load means loaded the trained model file with read binary mode

In [34]:
result=loaded_model.predict([[15]]) #this is final step which means we can see the linear regression output using by predict function

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [33]:
result #output check ,how much salary should be given to a employee with 15 years of experience

array([[111019.74291694]])